version: "3"

services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: basta
      MYSQL_DATABASE: basta
      MYSQL_USER: basta
      MYSQL_PASSWORD: basta

  app:
    depends_on:
      - db
    image: wordpress:6.1.1-php8.0-apache
    ports:
      - "8000:80"
      - "3000:3000"
      - "3001:3001"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: basta
      WORDPRESS_DB_PASSWORD: basta
      WORDPRESS_DB_NAME: basta
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/wp-content/themes/pmlogist:ro
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  db_data:
